version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123123
      MYSQL_DATABASE: saleswebsystem
      MYSQL_USER: user
      MYSQL_PASSWORD: 123123123
    ports:
      - "3306:3306"